name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: add softlink on header
      run: sudo ln -s $(pwd)/testlike.h /usr/include/testlike.h
    - name: make
      run: make
    - name: run tests pointers 
      run: ./test_ptr
    - name: run test int32
      run: ./test_int32
    - name: run test doubles
      run: ./test_dbl
    - name: clear all
      run: make clear
